cnoremap <C-A> <Home>
cnoremap <C-B> <Space><BS><Left>
cnoremap <C-Z> <S-Left>
cnoremap <C-F> <Space><BS><Right>
cnoremap <C-X> <S-Right>
cnoremap <C-G> <C-F>
cnoremap <C-D> <Del>
cnoremap <ESC>b <C-Left>
cnoremap <ESC>f <C-Right>
