noremap <leader>fa <ESC>:CtrlPBookmarkDir<CR>
noremap <leader>fb <ESC>:CtrlPBuffer<CR>
noremap <leader>fc <ESC>:CtrlPChange<CR>
noremap <leader>fd <ESC>:CtrlPDir<CR>
noremap <leader>ff <ESC>:CtrlP<CR>
noremap <leader>fl <ESC>:CtrlPLine<CR>
noremap <leader>fm <ESC>:CtrlPMRU<CR>
noremap <leader>ft <ESC>:CtrlPTag<CR>
noremap <leader>fq <ESC>:CtrlPQuickfix<CR>
